services:
  prateek-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Your_password123
    image: microsoft/mssql-server-linux
    container_name: prateek-db
    volumes:
      - ./data/mssql:/var/opt/mssql
    ports:
      - "1433"
  prateek-socialback:
    build: .
    container_name: prateek-socialback
    environment:
      SQLSERVER_HOST: Server=prateek-db;User=sa;Password=Your_password123
    links:
      - prateek-db
    ports:
      - "8089:5000"
    networks:
      - social_network
  neo4j:
    image: neo4j:latest
    ports:
      - "17474:7474"
      - "17687:7687"
    environment:
      - NEO4J_AUTH=neo4j/qwertyuiop
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
networks:
  social_network:
    external: true
version: "3"
